### ISSUE TITLE
Failure to build with openssl 1.1.0l

### ISSUE THREAD

**Issue by ederlf** [nginx/njs#636]
Trying to build nginx with the njs module, on a system using openssl 1.1.0l (debian stretch) I get many errors related to implicit declarations of openssl functions/constants.

(before I get a mention of how old is the debian/openssl versions I am trying to build: I am also not thrilled that I need to build stuff for those legacy versions :) )

```
In file included from /builds/vendor/nginx-package/dist/debian/modules/njs/nginx/../external/njs_webcrypto_module.c:9:0:
/builds/vendor/nginx-package/dist/debian/modules/njs/nginx/../external/njs_openssl.h: In function ‘njs_ec_point_get_affine_coordinates’:
/builds/vendor/nginx-package/dist/debian/modules/njs/nginx/../external/njs_openssl.h:307:12: error: implicit declaration of function ‘EC_POINT_get_affine_coordinates’ [-Werror=implicit-function-declaration]
     return EC_POINT_get_affine_coordinates(group, p, x, y, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/builds/vendor/nginx-package/dist/debian/modules/njs/nginx/../external/njs_webcrypto_module.c: In function ‘njs_export_jwk_asymmetric’:
/builds/vendor/nginx-package/dist/debian/modules/njs/nginx/../external/njs_webcrypto_module.c:2033:10: error: ‘EVP_PKEY_RSA_PSS’ undeclared (first use in this function)
     case EVP_PKEY_RSA_PSS:
          ^~~~~~~~~~~~~~~~
/builds/vendor/nginx-package/dist/debian/modules/njs/nginx/../external/njs_webcrypto_module.c:2033:10: note: each undeclared identifier is reported only once for each function it appears in
/builds/vendor/nginx-package/dist/debian/modules/njs/nginx/../external/njs_webcrypto_module.c: In function ‘njs_convert_der_to_p1363’:
/builds/vendor/nginx-package/dist/debian/modules/njs/nginx/../external/njs_webcrypto_module.c:3653:26: error: implicit declaration of function ‘ECDSA_SIG_get0_r’ [-Werror=implicit-function-declaration]
     if (njs_bn_bn2binpad(ECDSA_SIG_get0_r(ec_sig), data, n) <= 0) {
                          ^~~~~~~~~~~~~~~~
/builds/vendor/nginx-package/dist/debian/modules/njs/nginx/../external/njs_webcrypto_module.c:3653:26: error: passing argument 1 of ‘njs_bn_bn2binpad’ makes pointer from integer without a cast [-Werror=int-conversion]
In file included from /builds/vendor/nginx-package/dist/debian/modules/njs/nginx/../external/njs_webcrypto_module.c:9:0:
/builds/vendor/nginx-package/dist/debian/modules/njs/nginx/../external/njs_openssl.h:60:1: note: expected ‘const BIGNUM * {aka const struct bignum_st *}’ but argument is of type ‘int’
 njs_bn_bn2binpad(const BIGNUM *bn, unsigned char *to, int tolen)
 ^~~~~~~~~~~~~~~~
/builds/vendor/nginx-package/dist/debian/modules/njs/nginx/../external/njs_webcrypto_module.c:3657:26: error: implicit declaration of function ‘ECDSA_SIG_get0_s’ [-Werror=implicit-function-declaration]
     if (njs_bn_bn2binpad(ECDSA_SIG_get0_s(ec_sig), &data[n], n) <= 0) {
                          ^~~~~~~~~~~~~~~~
/builds/vendor/nginx-package/dist/debian/modules/njs/nginx/../external/njs_webcrypto_module.c:3657:26: error: passing argument 1 of ‘njs_bn_bn2binpad’ makes pointer from integer without a cast [-Werror=int-conversion]
In file included from /builds/vendor/nginx-package/dist/debian/modules/njs/nginx/../external/njs_webcrypto_module.c:9:0:
/builds/vendor/nginx-package/dist/debian/modules/njs/nginx/../external/njs_openssl.h:60:1: note: expected ‘const BIGNUM * {aka const struct bignum_st *}’ but argument is of type ‘int’
 njs_bn_bn2binpad(const BIGNUM *bn, unsigned char *to, int tolen)
 ^~~~~~~~~~~~~~~~
```

The errors seem related to changes made [4 months ago](https://github.com/nginx/njs/blame/master/external/njs_openssl.h#L306).
For example:

```
njs_inline int
njs_ec_point_get_affine_coordinates(const EC_GROUP *group, const EC_POINT *p,
    BIGNUM *x, BIGNUM *y)
{
#if (OPENSSL_VERSION_NUMBER >= 0x10100001L)
    return EC_POINT_get_affine_coordinates(group, p, x, y, NULL);
#else
    return EC_POINT_get_affine_coordinates_GFp(group, p, x, y, NULL);
#endif
}
```
Looking at the source code from openssl 1.1.0l, I could not find a reference for `EC_POINT_get_affine_coordinates`, only for `EC_POINT_get_affine_coordinates_GF2m` and `EC_POINT_get_affine_coordinates_GFp`.

I checked a couple of other 1.1.0<word> versions and they all have only the two functions above.

**Comment by xeioex** [comment]
hi @ederlf,

Feel free to test the following patch. It should build with OpenSSL down to 1.0.2.

```diff
# HG changeset patch
# User Dmitry Volyntsev <xeioex@nginx.com>
# Date 1683096260 25200
#      Tue May 02 23:44:20 2023 -0700
# Node ID 6633d26686b55969493ea889169a7806eaaf667f
# Parent  f1432043a6a4f722b5d97b8e41098bfd749b293a
WebCrypto: fixed building with OpenSSL 1.1.0.

This closes #636 issue on Github.

diff --git a/external/njs_openssl.h b/external/njs_openssl.h
--- a/external/njs_openssl.h
+++ b/external/njs_openssl.h
@@ -43,8 +43,6 @@
 #else
 #define njs_evp_md_ctx_new()  EVP_MD_CTX_create()
 #define njs_evp_md_ctx_free(_ctx)  EVP_MD_CTX_destroy(_ctx)
-#define ECDSA_SIG_get0_s(sig) (sig)->s
-#define ECDSA_SIG_get0_r(sig) (sig)->r
 #endif
 
 
@@ -303,7 +301,7 @@ njs_inline int
 njs_ec_point_get_affine_coordinates(const EC_GROUP *group, const EC_POINT *p,
     BIGNUM *x, BIGNUM *y)
 {
-#if (OPENSSL_VERSION_NUMBER >= 0x10100001L)
+#if (OPENSSL_VERSION_NUMBER >= 0x10101001L)
     return EC_POINT_get_affine_coordinates(group, p, x, y, NULL);
 #else
     return EC_POINT_get_affine_coordinates_GFp(group, p, x, y, NULL);
diff --git a/external/njs_webcrypto_module.c b/external/njs_webcrypto_module.c
--- a/external/njs_webcrypto_module.c
+++ b/external/njs_webcrypto_module.c
@@ -2024,7 +2024,7 @@ njs_export_jwk_asymmetric(njs_vm_t *vm, 
 
     switch (EVP_PKEY_id(key->pkey)) {
     case EVP_PKEY_RSA:
-#if (OPENSSL_VERSION_NUMBER >= 0x10100001L)
+#if (OPENSSL_VERSION_NUMBER >= 0x10101001L)
     case EVP_PKEY_RSA_PSS:
 #endif
         ret = njs_export_jwk_rsa(vm, key, retval);
@@ -3636,10 +3636,11 @@ static njs_int_t
 njs_convert_der_to_p1363(njs_vm_t *vm, EVP_PKEY *pkey, const u_char *der,
     size_t der_len, u_char **pout, size_t *out_len)
 {
-    u_char     *data;
-    unsigned   n;
-    njs_int_t  ret;
-    ECDSA_SIG  *ec_sig;
+    u_char        *data;
+    unsigned      n;
+    njs_int_t     ret;
+    ECDSA_SIG     *ec_sig;
+    const BIGNUM  *r, *s;
 
     ret = NJS_OK;
     ec_sig = NULL;
@@ -3659,11 +3660,18 @@ njs_convert_der_to_p1363(njs_vm_t *vm, E
         goto fail;
     }
 
-    if (njs_bn_bn2binpad(ECDSA_SIG_get0_r(ec_sig), data, n) <= 0) {
+#if (OPENSSL_VERSION_NUMBER >= 0x10100000L)
+    ECDSA_SIG_get0(ec_sig, &r, &s);
+#else
+    r = ec_sig->r;
+    s = ec_sig->s;
+#endif
+
+    if (njs_bn_bn2binpad(r, data, n) <= 0) {
         goto fail;
     }
 
-    if (njs_bn_bn2binpad(ECDSA_SIG_get0_s(ec_sig), &data[n], n) <= 0) {
+    if (njs_bn_bn2binpad(s, &data[n], n) <= 0) {
         goto fail;
     }
```

**Comment by xeioex** [comment]
Hi @ederlf,

I plan to commit the patch above, if you have any concerns or issues with it please let me know.

**Comment by ederlf** [comment]
Many thanks for your patch! That was super quick. :)

I won't be able to test it until tomorrow, so if you want to go ahead and
merge it's fine for me.

**Comment by xeioex** [comment]
hi @ederlf,

There is no rush from my side, feel free to test it as time permits.

**Comment by ederlf** [comment]
Hi @xeioex,

Gladly I've found a window of time to test it today. 
It builds with nginx and it seems to run fine too.

Once more, thanks for the super fast fix!
