### ISSUE TITLE
Crypto related functions failing randomly

### ISSUE THREAD

**Issue by xbb123** [nginx/njs#206]
Our NJS script is expericing random exceptions and core dumps with Crypto realted functions after upgrading to 0.3.4. 

2019/08/13 16:40:38 [error] 3664#3664: *3685 js exception: TypeError: (intermediate value)["createHash"] is not a function
    at checkAdminCookie (antiddos.js:910)
    at WAF (WAF.js:2)
2019/08/13 16:44:56 [alert] 983#983: worker process 3664 exited on signal 11 (core dumped)
2019/08/13 16:26:51 [error] 1834#1834: *478 js exception: Error: Cannot find module "md5"
    at require (native)
    at getIPHash (WAF.js:1059)
    at request.send (native)
    at sendTestPage1 (WAF.js:1072)
    at advancedBrowserTest (WAF.js:1045)
    at WAF (WAF.js:2)
`
function getIPHash(IP) {
	
	var s = "IPTokenKEY";
	s += IP;
	var d = new Date();
	var cr = require('crypto').createHash('md5')
		.update(s+d.getUTCFullYear()+d.getUTCMonth())
		.digest('base64url');
	return cr.toString();
}`

**Comment by xeioex** [comment]
Hi @xbb123 

Thank you for the report.

Can you reproduce the issue in njs cli?

**Comment by xbb123** [comment]
@xeioex We are unable to reproduce the issue in cli. The issue appears to be very random. Most of the time getIPHash can output the correct hash. But we can observe a lot of js exception and "InternalError: lvlhsh insert failed".
We are not using fs.readFileSync()

**Comment by xbb123** [comment]
@xeioex  One interesting finding.  This commit can reliably produce js exception: TypeError: (intermediate value)["createHash"] is not a function
![image](https://user-images.githubusercontent.com/13609473/62979903-09c32f80-bdf3-11e9-9c90-9d1e7d836869.png)

**Comment by xbb123** [comment]
We also have this under stress test:
 js exception: RangeError: Maximum call stack size exceeded
    at getIPHash (WAF.js:1059)

**Comment by xeioex** [comment]
@xbb123 Can you send me (xeioex at nginx.com) the minified njs file which still fails?

**Comment by xeioex** [comment]
@xbb123 

I can confirm that https://hg.nginx.org/njs/rev/04d7a5d93ae6 introduced the regression.

**Comment by xeioex** [comment]
@xbb123 

Please try the following patch: https://gist.github.com/xeioex/eb4f578478dec8bff40dc5984a15f356

**Comment by xbb123** [comment]
@xeioex The patch does pass all our test cases. It looks good 👍 
Given the nature of this issue, are we going to have a bug fix version soon?

**Comment by xeioex** [comment]
>  Given the nature of this issue, are we going to have a bug fix version soon?

Yes, the issue is quite serious because it impacts any configuration which uses `require()`.

**Comment by xeioex** [comment]
@xbb123 

BTW, as a workaround you can import crypto using import statement, it is not vulnerable.

```js
import crypto from 'crypto';

function getIPHash(IP) {
    crypto.createHash('md5') ...
}
```
