### ISSUE TITLE
Cannot compile on gcc 4.4

### ISSUE THREAD

**Issue by concatime** [nginx/njs#49]
Self-explanatory.
```
/opt/bin/musl-gcc -c -o build/nxt_strtod.o -D_GNU_SOURCE -pipe -fPIC -fvisibility=hidden -O -W -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wmissing-prototypes -Werror -g -march=native -O3 -pipe -g -O2 -ffunction-sections -fdata-sections --param=ssp-buffer-size=4 -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
		-Inxt \
		nxt/nxt_strtod.c
cc1: warnings being treated as errors
nxt/nxt_strtod.c: In function ‘nxt_adjust_pow10’:
nxt/nxt_strtod.c:115: error: control reaches end of non-void function
make[2]: *** [build/nxt_strtod.o] Error 1
```
