### ISSUE TITLE
Compilation issue with quickjs-ng >= 0.16.0

### ISSUE THREAD

**Issue by kaechele** [nginx/njs#1113]
### Describe the bug

njs will not compile with quickjs-ng >= 0.16.0

### To reproduce

Compile njs with quickjs-ng 0.16.1 and receive the following error:

```
gcc -c -Isrc -Iexternal -Ibuild -fPIC -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer   -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer \
	 \
	-o build/src/qjs.o \
	-MMD -MF build/src/qjs.dep -MT build/src/qjs.o \
	src/qjs.c
src/qjs.c: In function ‘qjs_new_array_buffer’:
src/qjs.c:1183:44: error: passing argument 4 of ‘JS_NewArrayBuffer’ makes integer from pointer without a cast [-Wint-conversion]
 1183 |     return JS_NewArrayBuffer(cx, src, len, js_array_buffer_free, NULL, 0);
      |                                            ^~~~~~~~~~~~~~~~~~~~
      |                                            |
      |                                            void (*)(JSRuntime *, void *, void *)
In file included from src/quickjs_compat.h:15,
                 from src/qjs.h:22,
                 from src/qjs.c:7:
/usr/include/quickjs.h:1087:44: note: expected ‘size_t’ {aka ‘long unsigned int’} but argument is of type ‘void (*)(JSRuntime *, void *, void *)’
 1087 |                                     size_t max_len,
      |                                     ~~~~~~~^~~~~~~
src/qjs.c:1183:12: error: too few arguments to function ‘JS_NewArrayBuffer’; expected 7, have 6
 1183 |     return JS_NewArrayBuffer(cx, src, len, js_array_buffer_free, NULL, 0);
      |            ^~~~~~~~~~~~~~~~~
/usr/include/quickjs.h:1086:19: note: declared here
 1086 | JS_EXTERN JSValue JS_NewArrayBuffer(JSContext *ctx, uint8_t *buf, size_t len,
      |                   ^~~~~~~~~~~~~~~~~
```

### Expected behavior

njs compiles.

### Your environment

- njs latest master (85e2ff5b770ce37e4cd96ae1366a564d62a76e45 at time of reporting)
- quickjs-ng 0.16.1
- OS: Fedora 44

### Additional context

The quickjs-ng API change was introduced in with the following commit: https://github.com/quickjs-ng/quickjs/commit/6a2c5f362c4cc8198ad6d0c2927de99865eef4e3

Likely means that things like `#if defined(QUICKJS_NG) && (QJS_VERSION_MAJOR >= 0 && QJS_VERSION_MINOR >= 16)` will become a more common occurrence with quickjs and quickjs-ng diverging.

**Comment by bnoordhuis** [comment]
#1114 should fix that (also includes a fix for a runtime issue.) I'll see about adding njs to the quickjs-ng CI.
