### ISSUE TITLE
njs cannot build with libxml 2.12.0

### ISSUE THREAD

**Issue by hshh** [nginx/njs#684]
OS: Arch Linux aarch64
njs version: git 9de301351c28f1506f9fc4e20cfd40e121fb7b2e
nginx version: 1.25.3
libxml2 version: 2.12.0-1

compile error info,

```
clang -c -pipe  -O -Wall -Wextra -Wpointer-arith -Wconditional-uninitialized -Wno-unused-parameter -Werror -g -O3 -pipe -fno-strict-aliasing -ftree-vectorize -flto=thin  -I src/core -I src/event -I src/event/modules -I src/event/quic -I src/os/unix -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/v2 -I /data/src/njs/nginx/../src -I /data/src/njs/nginx/../build -I src/mail -I src/stream -I /data/src/njs/nginx/../src -I /data/src/njs/nginx/../build \
        -o objs/addon/nginx/ngx_stream_js_module.o \
        /data/src/njs/nginx/ngx_stream_js_module.c
/data/src/njs/nginx/../external/njs_xml_module.c:2000:9: error: assigning to 'xmlError *' (aka 'struct _xmlError *') from 'const xmlError *' (aka 'const struct _xmlError *') discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
    err = xmlCtxtGetLastError(current->ctx);
        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [objs/Makefile:1917: objs/addon/external/njs_xml_module.o] Error 1
make[1]: Leaving directory '/data/src/nginx-1.25.3'
make: *** [Makefile:10: build] Error 2
```

I can build with libxml2 2.11.5
